version: '3'
services:
  mysql:
    image: "mysql:5.7"
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=YueXinShiDai
    ports:
      - "33066:3306"
  queue:
    build: ./queue
    volumes:
      - ${WWW_DIR}:/var/www
      - ${APP_DIR}:/app/app
      - ${PROJECT_DIR}:/home/test
    command: ["/usr/bin/php","/var/www/artisan","queue:work","--queue=yx"]
    links:
      - mysql
  web:
    build: ./web
    volumes:
      - ${WWW_DIR}:/var/www
      - ${APP_DIR}:/app/app
      - ${PROJECT_DIR}:/home/test
    ports:
      - "80:80"
    links:
      - mysql
  